# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: todo-app-heroku

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Copy heroku Dockerfile
        # You may pin to the exact commit or the version.
        # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
        uses: canastro/copy-action@0.0.2
        with:          
          source: ./.heroku/Dockerfile          
          target: ./Dockerfile    
          
      - name: Build, Push and Deploy to Heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: './'
          options: -f Dockerfile.web
          formation: 'web'

