name: Run Unit Tests

on:  
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run Unit Test
      run: dotnet test --verbosity normal
